# Generated by Django 4.0.4 on 2022-06-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='like'),
        ),
    ]
